version: "3.9"

services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    restart: always

  app:
    image: 344393402524.dkr.ecr.ap-southeast-1.amazonaws.com/pvicard-staging:v1
    env_file:
      - ./.env.app
    volumes:
      - static_data:/static
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: ./nginx
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - static_data:/static
      - ./letsencrypt/conf:/etc/letsencrypt
      - ./letsencrypt/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt/conf:/etc/letsencrypt
      - ./letsencrypt/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

volumes:
  static_data:
  postgres_data:
